# Generated by Django 4.0.1 on 2022-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default='null', max_length=255, verbose_name='ID транзакции'),
        ),
    ]
